Repository reviewdog/action-golangci-lint, pull requests merged in 2020-05, with the labels that each got.

#31 Update workflow
  .github/workflows/depup.yml
  .github/workflows/release.yml
  .github/workflows/update_semver.yml
  Dockerfile
  README.md
Labels: bump:patch

#35 Added new flags introduced by reviewdog v0.10.0
  README.md
  action.yml
  entrypoint.sh
Labels: bump:minor

#37 Do not recomment to use pre-built image
  README.md
Labels: bump:patch

#38 Provide default Github token
  .github/workflows/reviewdog.yml
  README.md
  action.yml
Labels: bump:minor, documentation, enhancement

#15 feature: add directory argument
  .github/workflows/reviewdog.yml
  README.md
  action.yml
  entrypoint.sh
  testdata/main.go
Labels: bump:minor
